### ISSUE TITLE
Website icon content \27

### ISSUE THREAD

**Issue by viktorgardart** [driftyco/ionicons#264] opened 2015-06-03 13:10 UTC
All the icons on [the website](http://ionicons.com/) is showning the wrong content, all of them shows `\27`

**Comment by albinekb** [comment] 2015-06-03 13:12
![image](https://cloud.githubusercontent.com/assets/5027156/7960719/e025104c-0a02-11e5-8e1e-9fe6a267f810.png)

**Comment by donny85** [comment] 2015-06-06 16:33
Duplicate of #228 ...

**Closed** 2015-12-30 19:12 UTC
Labels: ionitron:closed
