### ISSUE TITLE
Published to NPM

### ISSUE THREAD

**Issue by tbranyen** [driftyco/ionicons#285] opened 2015-07-20 13:34 UTC
Hi ya'll, I published this package's version 2.0.1 to NPM under the name `ionicons`.  If the owners would like to take over, I'd be happy to make a PR that includes the `.npmignore` and `package.json` files necessary, as well as remove myself and add them as the owner.  If they don't and new versions come out, please ping me in here and I'll publish the new version.

**Comment by coderbyheart** [comment] 2015-08-24 17:06
Dupe of #129

**Closed** 2015-12-30 19:12 UTC
Labels: ionitron:closed
